crm/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView 
from . import views

app_name = "crm"
urlpatterns = [
    path('login/' , login_view.as_view() , name="login"),
    path('logout/' , views.logoutView , name='logout'),
    path('registration/' , registrationView.as_view() , name="registration"),
    path('home/' , CrmView.as_view() , name="crm-view"),
    path('home/<int:pk>/' , CrmDetailView.as_view() , name="detail"),
    path('home/<int:pk>/delete/' , DeleteCrmView.as_view() , name="delete"),
    path('home/<int:pk>/update/' , UpdateCrmView.as_view() , name='update'),
    path('new/' , CreateCrmView.as_view() , name="new"),
]

management/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include("crm.urls")),
]

crm/models.py
from typing import Iterable
from django.db import models

# Create your models here.

class Customer(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=11)
    address = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    nationalID = models.CharField(max_length=14)
    Custom_id = models.PositiveIntegerField(unique=True , null=True , blank=True)
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    def save(self,*args , **kwargs):
        if self.Custom_id is None:
            last_customer = Customer.objects.all().order_by('Custom_id').last()
            if last_customer :
                self.Custom_id = last_customer.Custom_id + 1
            else:
                self.Custom_id = 1
        super().save(*args , **kwargs)

crm/views.py
from django.shortcuts import render ,redirect
from django.contrib.auth.views import LoginView , LogoutView
from django.contrib.auth import get_user_model
from django.views.generic import ListView , DetailView , DeleteView , UpdateView , CreateView
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login , authenticate , logout
from django.urls import reverse_lazy
from .models import Customer
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

class login_view(LoginView):
    template_name = 'pages/login.html'
    fields = "__all__"
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy("crm:crm-view")
    
class registrationView(FormView):
    template_name = "pages/registration.html"
    form_class = UserCreationForm
    success_url = reverse_lazy("crm:login")

    def form_valid(self, form) :
        user = form.save()
        if user is not None:
            login(self.request,user)
        return super(registrationView , self).form_valid(form)
    
    def get(self,*args,**kwargs ):
        if self.request.user.is_authenticated :
            return redirect('Edu:login')
        return super(registrationView , self ).get(*args,**kwargs)

class CrmView(LoginRequiredMixin,ListView):
    queryset = Customer.objects.all()
    template_name = "pages/home.html"
    context_object_name = 'customers'
    login_url = reverse_lazy('crm:login')
class CrmDetailView(LoginRequiredMixin , DetailView):
    queryset = Customer.objects.all()
    template_name = "pages/detail.html"
    context_object_name = "customersDetails"
    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

class DeleteCrmView(LoginRequiredMixin , DeleteView):
    queryset = Customer.objects.all()
    template_name = 'pages/delete.html'
    success_url = reverse_lazy('crm:crm-view')


class UpdateCrmView(LoginRequiredMixin , UpdateView):
    model = Customer
    fields = "__all__"
    template_name = 'pages/update.html'
    context_object_name = 'customer'
    success_url = reverse_lazy('crm:crm-view')

class CreateCrmView(LoginRequiredMixin , CreateView):
    model = Customer
    fields = "__all__"
    template_name = 'pages/create.html'
    success_url = reverse_lazy('crm:crm-view')
    context_object_name = 'customer'

def logoutView(request):
    logout(request)
    return redirect('crm:login')

crm/templates/pages/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">CRM App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'crm:crm-view' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'crm:logout' %}" class="nav-link">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'crm:login' %}" class="nav-link active">Login</a>
                    </li>
                {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    {% block content %}
    {% endblock content %}
</body>
</html>

crm/templates/pages/create.html
{% extends 'pages/base.html' %}


{% block content %}
    <h1> Create New Customer </h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-dark" value="Create">
    </form>
{% endblock content %}

crm/templates/pages/delete.html
{% extends 'pages/base.html' %}


{% block content %}
    <h1> Confirm Deletion </h1>

    <p>Are you sure you want to delete {{customersDetails.first_name}} {{customersDetails.last_name}} record? </p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Confirm" class="btn btn-danger" id="">
        <a href="{% url 'crm:crm-view' %}" class="btn btn-dark">Cancel</a>
    </form>
{% endblock content %}

crm/templates/pages/detail.html
{% extends 'pages/base.html' %}

{% block content %}
<h1>Customer Detail</h1>
<div class="card m-5" style="width: fit-content;">
    <div class="card-header">
      {{customersDetails.first_name}}
      {{customersDetails.last_name}}
    </div>
    <div class="card-body">
      
      <p class="card-text">
        
        <strong> Email : </strong> {{customersDetails.email}} <br>
        <strong> Adress : </strong> {{customersDetails.address}} <br>
        <strong> Phone : </strong> {{customersDetails.phone}} <br>
        <strong> Country : </strong> {{customersDetails.country}} <br>
        <strong> City : </strong> {{customersDetails.city}} <br>
        <strong> National id : </strong> {{customersDetails.nationalID}} <br>
      </p>
      <a href="{% url 'crm:update' customersDetails.id %}" class="btn btn-dark">update</a>
      <a href="{% url 'crm:delete' customersDetails.id %}" class="btn btn-danger">Delete</a>
    </div>
  </div>
{% endblock content %}

crm/templates/pages/home.html
{% extends 'pages/base.html' %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Customer List</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 8px 12px;
            border: 1px solid #ccc;
        }
        th {
            background-color: #f4f4f4;
        }
    </style>
</head>
<body>
    <h1>Customer List</h1>
    <table class="table table-striped table-hover">
        <thead class="text-light bg-dark">
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Country</th>
                <th>City</th>
                <th>National ID</th>
            </tr>
        </thead>
        <tbody>
            {% for customer in customers %}
            <tr>
                <td><a href="{% url 'crm:detail' customer.id %}" style="text-decoration: none; color: black;"> {{ customer.Custom_id }}</a></td>
                <td>{{ customer.first_name }}</td>
                <td>{{ customer.last_name }}</td>
                <td>{{ customer.email }}</td>
                <td>{{ customer.phone }}</td>
                <td>{{ customer.address }}</td>
                <td>{{ customer.country }}</td>
                <td>{{ customer.city }}</td>
                <td>{{ customer.nationalID }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'crm:new' %}" class="btn btn-dark"> Add New Customer </a>
</body>
</html>

{% endblock content %}

crm/templates/pages/login.html
{% extends 'pages/base.html' %}

{% block content %}
<div class="col-md-6 offset-md-1 mt-3">
    <h3>Login</h3>
    <br>
    <form action="{% url 'crm:login' %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Login" id="input" class="btn btn-dark">
    </form>
</div>
{% endblock content %}

crm/templates/pages/logout.html
{% extends 'pages/base.html' %}


{% block content %}

    <h1>Confirm Logging out</h1>

    <form action="{% url 'crm:login' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Confirm">
        <a href="{% url 'crm:crm-view' %}">Cancel</a>
    </form>
{% endblock content %}

crm/templates/pages/registration.html
{% extends 'pages/base.html' %}

{% block content %}
<form action="{% url 'crm:registration' %}" method="post">
    <h3>Registration Form</h3>
    {{form.as_p}}
    <input type="submit" class="btn btn-dark">
</form>
{% endblock content %}

crm/templates/pages/update.html
{% extends 'pages/base.html' %}


{% block content %}

    <form action="{% url 'crm:update' customer.id %}" method="post">
        {% csrf_token %}
        {{form.as_p}}

        <input type="submit" value="Update" class="btn btn-dark">
    </form>
{% endblock content %}